Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EFDataModel

    Partial Public Class Customer
        Public Property ID() As Integer
        Public Property FirstName() As String
        Public Property LastName() As String
        Public Property Company() As String
        Public Property Address() As String
        Public Property City() As String
        Public Property State() As String
        Public Property ZipCode() As String
        Public Property HomePhone() As String
    End Class
End Namespace
