Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EFDataModel

    Partial Public Class ContactsEntities
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=ContactsEntities")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub

        Public Overridable Property Customers() As DbSet(Of Customer)
        Public Overridable Property Totals() As DbSet(Of Total)
        Public Overridable Property CustomersPayments() As DbSet(Of CustomersPayment)
    End Class
End Namespace
