Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EFDataModel

    Partial Public Class Total
        Public Property ID() As Integer
        Public Property CustomerID() As Integer?
        Public Property Year() As Short?
        Public Property January() As Double?
        Public Property February() As Double?
        Public Property March() As Double?
        Public Property April() As Double?
        Public Property May() As Double?
        Public Property June() As Double?
        Public Property July() As Double?
        Public Property August() As Double?
        Public Property September() As Double?
        Public Property October() As Double?
        Public Property November() As Double?
        Public Property December() As Double?
    End Class
End Namespace
